config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'quotes#index'

  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    @quotes = Quote.all.paginate(:page => params[:page], :per_page => 12).order('id DESC')
  end

  def new

  end

  def create
    @quote = Quote.new(post_params)
    @quote['date_published'] = Time.now
    @quote.save

    redirect_to '/'
  end

  private def post_params
    params.require(:quote).permit(:quote)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anonymous Quotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
         <div class="navbar navbar-dark bg-dark shadow-sm">
           <div class="container d-flex justify-content-between">
             <a href="/" class="navbar-brand d-flex align-items-center">
               <strong>Anonymous Quotes</strong>
             </a>
             <a href="/quotes/new" class="navbar-brand d-flex align-items-center">
             <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               Add quote
             </button>
           </a>
           </div>
         </div>
       </header>

    <%= yield %>
  </body>
</html>

<!-- Author: Surrerstry -->

app/views/quotes/index.html.erb
<center>
<br />
<i><u><h1>&nbsp;List of quotes&nbsp;</h1></u></i>
<br />

<div class="container">

  <hr />

  <div class="row">
    <% @quotes.each do |quote| %>
      <div class="col-md-4">
        <br />
        <p><b>"<i><%= quote.quote %></i>"</b></p>
        <p style="font-size:11px"><tt><%= quote.date_published.strftime('%d %B %Y') %></tt></p>
      </div>
      <% end %>
  </div>

  <hr />

</div>

<br />

<div style="text-align:center !important; display:block !important">
  <%= will_paginate @quotes, :container => false %>
</div>

</center>

app/views/quotes/new.html.erb
<center>
<br />
<i><u><h1>&nbsp;Add quote&nbsp;</h1></u></i>
<br />

<%= form_for :quote, url: quotes_path do |f| %>
  <p>
    <%= f.label :quote %><br />
    <%= f.text_field :quote %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
</center>